### ISSUE TITLE
Wireguard fails

### ISSUE THREAD

**Issue by omegion** [hobby-kube/provisioning#62]
It fails when it tries to start the service:
```
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
```

```
Building for 4.15.0-99-generic
Building initial module for 4.15.0-99-generic
Error! Bad return status for module build on kernel: 4.15.0-99-generic (x86_64)
Consult /var/lib/dkms/wireguard/1.0.20200611/build/make.log for more information.
root@k8s-2:~# cat /var/lib/dkms/wireguard/1.0.20200611/build/make.log
DKMS make.log for wireguard-1.0.20200611 for kernel 4.15.0-99-generic (x86_64)
Wed Jun 24 16:24:38 CEST 2020
make: Entering directory '/usr/src/linux-headers-4.15.0-99-generic'
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/main.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/noise.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/device.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/peer.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/timers.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/queueing.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/send.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/receive.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/socket.o
/var/lib/dkms/wireguard/1.0.20200611/build/socket.c: In function ‘send6’:
/var/lib/dkms/wireguard/1.0.20200611/build/socket.c:139:20: error: ‘const struct ipv6_stub’ has no member named ‘ipv6_dst_lookup_flow’; did you mean ‘ipv6_dst_lookup’?
   dst = ipv6_stub->ipv6_dst_lookup_flow(sock_net(sock), sock, &fl,
                    ^~~~~~~~~~~~~~~~~~~~
                    ipv6_dst_lookup
scripts/Makefile.build:330: recipe for target '/var/lib/dkms/wireguard/1.0.20200611/build/socket.o' failed
make[1]: *** [/var/lib/dkms/wireguard/1.0.20200611/build/socket.o] Error 1
Makefile:1577: recipe for target '_module_/var/lib/dkms/wireguard/1.0.20200611/build' failed
make: *** [_module_/var/lib/dkms/wireguard/1.0.20200611/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.0-99-generic'
```

**Comment by omegion** [comment]
I had to update ubuntu kernel and reboot the nodes:
```
apt-get install -y --install-recommends linux-generic-hwe-18.04
apt-get -y dist-upgrade
```

**Comment by 4ndrewHarri5** [comment]
Hi. I get the same errors with wireguard along with six `Error: error executing "/tmp/terraform_xxxxxxxxx.sh": Process exited with status 1` error messages. I tried your suggestion performing those commands in all 3 ubuntu servers, then running `terraform apply` again but with no luck.

**Comment by pstadler** [comment]
With which provider does this happen?

**Comment by RolfKoenders** [comment]
I had this issue with the Hetzner cloud. The solution from @omegion solved it for me.

**Comment by 4ndrewHarri5** [comment]
@pstadler I tried it in Hetzner cloud, scaleway and digital ocean. Cheers

**Comment by rzkmak** [comment]
got same issue with digitalocean here, tried @omegion solution and it works!

**Comment by pstadler** [comment]
Thanks for all your feedback! Going to add a fix across all providers in this case.

**Comment by pstadler** [comment]
Couldn't reproduce this on Hetzner Cloud.

**Comment by pstadler** [comment]
This shouldn't be a problem any longer. With Ubuntu 20.04, a simple `apt install wireguard` is enough.
